<script lang="ts">
  import { onMount } from 'svelte';
  import { browser } from '$app/environment';
  import { contentFor, type Locale } from '$lib/content';
  import StickyCta from '$lib/components/StickyCta.svelte';
  import Testimonials from '$lib/components/Testimonials.svelte';
  import { resolveAnchor } from '$lib/stage/poses';
  import { stage } from '$lib/stage/store.svelte';
  import { buildSiteJsonLd, SITE_URL } from '$lib/seo/structured-data';
  import type { PageProps } from './$types';

  /*
    `.flod`, `<FlodStage>`, `<SiteHeader>`, `<ContactSection>`,
    `<SiteFooter>` — all now live in the shared `(app)/+layout.svelte`
    shell. This page contributes only the homepage's own content:
    chapter wraps, sections, testimonials. Stage state is published
    through the `stage` store so the layout's persistent FlodStage
    picks it up.
  */

  let { data }: PageProps = $props();

  // All page-level derived state reacts to `data.locale` so client-side
  // navigation between `/` and `/en` updates head + content in lockstep.
  const locale: Locale = $derived(data.locale);
  const bundle = $derived(contentFor(locale));
  const site = $derived(bundle.site);
  const contact = $derived(bundle.contact);
  const bio = $derived(bundle.bio);
  const home = $derived(bundle.home);
  const services = $derived(bundle.services);
  /*
    Look up services by their stable cross-locale `id` (derived from
    the content filename), NOT by `slug` — slugs are localised
    (e.g. DA `intimitetskoordinering` vs EN `intimacy-coordination`)
    and differ per locale, while the id stays constant. Was `s.slug`
    before per-locale slugs landed, which made intimacy-coordination
    disappear on the DA homepage.
  */
  const findService = (id: string) => services.find((s) => s.id === id);

  const jsonLd = $derived(JSON.stringify(buildSiteJsonLd({ site, bio, contact, services })));

  // Canonical + hreflang helpers. DA is prefix-less; EN lives at /en.
  const canonicalUrl = $derived(`${SITE_URL}${locale === 'en' ? '/en' : '/'}`);
  const daUrl = `${SITE_URL}/`;
  const enUrl = `${SITE_URL}/en`;
  const ogLocale = $derived(locale === 'en' ? 'en_US' : 'da_DK');
  const ogLocaleAlternate = $derived(locale === 'en' ? 'da_DK' : 'en_US');

  // Title + description derived from the active locale's content.
  const metaTitle = $derived(`${site.name} · ${site.tagline}`);
  const metaDescription = $derived(
    `${site.leadIn} — ${services.map((s) => s.title).join(' · ')}`
  );
  const ogDescription = $derived(site.tagline);

  // Locale-specific OG image generated by `pkgx pnpm og` (Playwright
  // screenshot of /og/home for DA, /og/en/home for EN).
  const ogImageUrl = $derived(`${SITE_URL}/img/og/home.${locale}.jpg`);

  // Chapter state — flips to 1 once the Konsulentydelser section scrolls
  // into the upper half of the viewport. Drives the FlodStage material
  // cross-fade. The bg is a hard-stop linear gradient on `.flod` whose
  // split-line (`--konsulent-y`) is the pixel position of the chapter
  // divider within `.flod`, so the warm paper bg behaves as if it's
  // scrolling up behind the 3D stage from the chapter-II line.
  //
  // Sticky CTAs (Book en tid / Kom i kontakt) are CSS-driven —
  // `position: sticky` inside their chapter-wrap divs. chapter-wrap-
  // konsulent now extends through the bio section so Kom i kontakt
  // stays pinned through the whole about-section and only releases
  // at the boundary with the contact block. (The exact-alignment
  // with the "Skriv." heading the user mentioned would require
  // restructuring contact in the DOM — deferred to a separate pass.)
  let chapterMode = $state(0);
  let konsulentY = $state<number | null>(null);

  onMount(() => {
    if (!browser) return;
    // `.flod` is rendered by the (app) layout. The chapter-II
    // divider is measured at the TOP of chapter-wrap-konsulent
    // (the konsulent wrap's border-box top sits exactly at the
    // chapter boundary), so the bg gradient hard-stop stays in
    // step with where the user actually sees the text change.
    const flodEl = document.querySelector('.flod') as HTMLElement | null;
    const konsulentWrapEl = document.querySelector('.chapter-wrap-konsulent');
    if (!flodEl || !konsulentWrapEl) return;
    let raf = 0;
    const measure = () => {
      const flodRect = flodEl.getBoundingClientRect();
      const wrapRect = konsulentWrapEl.getBoundingClientRect();
      // Divider-top relative to .flod's top — feeds the bg
      // gradient's hard-stop via the shared store.
      konsulentY = wrapRect.top - flodRect.top;
      // Smooth chapter progression (continuous, not binary): 0
      // when the divider is well below the fold, 1 when it has
      // scrolled past the upper band. FlodStage lerps materials
      // along this value for a scroll-driven palette transition.
      const vh = window.innerHeight;
      const startY = vh * 0.75; // begin crossfade at 75% of viewport
      const endY = vh * 0.15; // full konsulent when divider is at 15%
      const raw = (startY - wrapRect.top) / Math.max(1, startY - endY);
      chapterMode = Math.max(0, Math.min(1, raw));
    };
    const onScroll = () => {
      if (raf) return;
      raf = requestAnimationFrame(() => {
        raf = 0;
        measure();
      });
    };
    window.addEventListener('scroll', onScroll, { passive: true });
    window.addEventListener('resize', onScroll, { passive: true });
    // Re-measure after fonts/layout settle
    measure();
    const t = setTimeout(measure, 300);
    return () => {
      window.removeEventListener('scroll', onScroll);
      window.removeEventListener('resize', onScroll);
      clearTimeout(t);
      if (raf) cancelAnimationFrame(raf);
    };
  });

  /*
    Publish this page's stage state to the shared store. The
    layout's single FlodStage mount consumes it and lerps
    internally between publishes — so scroll updates on this
    page animate smoothly, and client-side navigation to a
    service page sees the store mutate to the new anchors and
    eases the stage to the new pose without remounting.
  */
  $effect(() => {
    stage.anchors = home.stage.sections.map(resolveAnchor);
  });
  $effect(() => {
    stage.chapterMode = chapterMode;
  });
  $effect(() => {
    stage.konsulentY = konsulentY;
  });

  // Section sequence:
  //   hero → who → CHAPTER I · Terapi (manifest, ritual, therapy service, for-personal)
  //        → CHAPTER II · Konsulentydelser (intimacy + embedded testimonial, elderly, teaching, for-work)
  //        → bio → contact
  //
  // Page content + per-section stage config live in `src/content/da/home.json`.
  // Each section declares named poses from $lib/stage/poses for the three
  // WebGL elements (mercury orb, gold metaballs, faceted gem). Poses resolve
  // to NDC coordinates at runtime. Section ids become `data-stage-anchor`
  // attributes on the corresponding section roots; FlodStage queries by that
  // attribute rather than brittle positional CSS selectors.
  // Per-section home content — each grouped under its section name in
  // home.json, so the destructuring here mirrors the site structure
  // rather than a flat string bag.
  const nav = $derived(home.nav);
  const hero = $derived(home.hero);
  const nameSection = $derived(home.nameSection);
  const chapter1 = $derived(home.chapter1);
  const manifest = $derived(home.manifest);
  const ritual = $derived(home.ritual);
  const forPersonal = $derived(home.forPersonal);
  const chapter2 = $derived(home.chapter2);
  const pillQuote = $derived(home.pillQuote);
  const forWork = $derived(home.forWork);
  // Individual services by id so each section can compose its own
  // bespoke layout (services are intentionally NOT rendered by one
  // shared component — see AGENTS.md).
  const therapyService = $derived(findService('terapi'));
  const intimacyService = $derived(findService('intimacy-coordination'));
  const elderlyService = $derived(findService('aeldrepleje'));
  const teachingService = $derived(findService('undervisning'));
</script>

<svelte:head>
  <title>{metaTitle}</title>
  <meta name="description" content={metaDescription} />
  <meta name="author" content={site.name} />
  <meta name="theme-color" content="#f3ede2" />

  <!-- Open Graph — Facebook, LinkedIn, generic link previews. -->
  <meta property="og:site_name" content={site.name} />
  <meta property="og:title" content={site.name} />
  <meta property="og:description" content={ogDescription} />
  <meta property="og:type" content="website" />
  <meta property="og:locale" content={ogLocale} />
  <meta property="og:locale:alternate" content={ogLocaleAlternate} />
  <meta property="og:url" content={canonicalUrl} />
  <meta property="og:image" content={ogImageUrl} />
  <meta property="og:image:alt" content={site.name} />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:type" content="image/jpeg" />

  <!-- Twitter / X — uses its own meta namespace. -->
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content={site.name} />
  <meta name="twitter:description" content={ogDescription} />
  <meta name="twitter:image" content={ogImageUrl} />

  <link rel="canonical" href={canonicalUrl} />
  <!--
    hreflang alternates — each locale's page references itself + the
    other locale + x-default (DA). Best-practice SEO signal that tells
    Google which version to serve to which user.
  -->
  <link rel="alternate" hreflang="da" href={daUrl} />
  <link rel="alternate" hreflang="en" href={enUrl} />
  <link rel="alternate" hreflang="x-default" href={daUrl} />

  <!--
    Schema.org structured data — a single @graph with the business,
    Signe as Person, and each service as a Service node. Built from
    the active locale's content so the graph reads in the right
    language for the page it's on.
    https://schema.org / https://search.google.com/test/rich-results
  -->
  {@html `<script type="application/ld+json">${jsonLd}</script>`}
</svelte:head>

<!--
  Chapter I wrapper. The therapy CTA sits as the first child so its
    sticky-bottom position engages from the top of the scrollable area;
    it stays pinned until the chapter-wrap's bottom (the end of
    for-personal) scrolls up past the sticky threshold, at which point
    the button scrolls up naturally with the container. No JS required.
  -->
  <div class="chapter-wrap chapter-wrap-therapi">
    {#if therapyService?.cta}
      <StickyCta cta={therapyService.cta} />
    {/if}

  <!--
    Hero is a section, not a <header> — the page-level banner is
    `.top` above, and using <header> here would give the hero its
    own implicit banner role inside <main>, competing with `.top`
    for assistive-tech attention.
  -->
  <section class="hero" data-stage-anchor="hero">
    <p class="name-card reveal-slide">
      {hero.name}<br />
      <span>{hero.city}</span>
    </p>
    <h1 class="statement">
      <span class="line reveal-soft"><span class="ink">{hero.statementStart}</span></span>
      <span class="line reveal-soft em">
        <span class="ink">{hero.statementEnd}</span><em>{hero.statementEm}</em><span class="ink dot">.</span>
      </span>
    </h1>
    <p class="attribution reveal">
      {hero.attribution}
    </p>
    <div class="hero-scroll">
      <span>{hero.scrollLabel}</span>
      <span class="arrow">↓</span>
    </div>
  </section>

  <section class="name-section" data-stage-anchor="name-section">
    <div class="name-grid">
      <div class="reveal-slide">
        <p class="eyebrow">{nameSection.eyebrow}</p>
        <h2>
          {nameSection.firstName} <em>{nameSection.lastName}</em>
        </h2>
        <p class="pronouns">{nameSection.pronouns}</p>
      </div>
      <div class="reveal">
        <p class="role-line">{nameSection.roleLine}</p>
        <p class="role-sub">{nameSection.roleSub}</p>
      </div>
    </div>
  </section>

  <!-- ============== CHAPTER I · TERAPI ============== -->
  <section class="chapter chapter-terapi" data-stage-anchor="chapter-terapi">
    <div class="chapter-inner reveal">
      <p class="chapter-mark">{chapter1.mark}</p>
      <h2 class="chapter-title">{chapter1.title}</h2>
      <p class="chapter-lede">{chapter1.lede}</p>
    </div>
  </section>

  <section class="manifest" data-stage-anchor="manifest">
    <p class="section-label reveal">{manifest.label}</p>
    <ul>
      {#each manifest.items as m, i}
        <li class="reveal">
          <span class="m-num">{String(i + 1).padStart(2, '0')}</span>
          <p>
            {#each m.text.split(m.word) as part, j}
              {part}{#if j < m.text.split(m.word).length - 1}<em>{m.word}</em>{/if}
            {/each}
          </p>
        </li>
      {/each}
    </ul>
  </section>

  <section class="ritual" data-stage-anchor="ritual">
    <div class="ritual-head reveal">
      <p class="section-label">{ritual.label}</p>
      <h2>{ritual.subtitle}</h2>
    </div>
    <ol class="ritual-list">
      {#each ritual.steps as step}
        <li class="reveal">
          <span class="r-n">{step.n}</span>
          <div>
            <h3>{step.title}</h3>
            <p>{step.body}</p>
          </div>
        </li>
      {/each}
    </ol>
  </section>

  {#if therapyService}
    <section class="service service-terapi" id={therapyService.slug} data-stage-anchor="service-terapi">
      <div class="service-head reveal">
        <span class="s-num">{therapyService.number}</span>
        <span class="s-kicker">{therapyService.kicker}</span>
      </div>
      <h2 class="service-title reveal">{therapyService.title}</h2>
      <p class="s-blurb reveal">{therapyService.blurb}</p>
      <ul class="s-bullets reveal">
        {#each therapyService.bullets as bullet}
          <li>{bullet}</li>
        {/each}
      </ul>
      {#if therapyService.supports && therapyService.supportsLabel}
        <div class="s-supports-block reveal">
          <p class="s-supports-label">{therapyService.supportsLabel}</p>
          <p class="s-supports">{therapyService.supports.join(' · ')}</p>
        </div>
      {/if}
    </section>
  {/if}

  <section class="for-personal" data-stage-anchor="for-personal">
    <p class="section-label reveal">{forPersonal.label}</p>
    <ul>
      {#each forPersonal.items as reason, i}
        <li class="reveal" style="--d: {i * 60}ms">
          <span class="fy-num">{String(i + 1).padStart(2, '0')}</span>
          <span>{reason}</span>
        </li>
      {/each}
    </ul>
  </section>

  </div><!-- /.chapter-wrap-therapi -->

  <!-- ============== CHAPTER II · KONSULENTYDELSER ============== -->
  <!--
    chapter-wrap-konsulent extends through the bio section so
    `Kom i kontakt` stays sticky all the way to the contact block.
    The StickyCta is the wrap's first child so it's sticky-bound by
    the wrap itself (sticky's containing block = nearest block-level
    parent, not nearest positioned ancestor — placing it inside
    chapter-konsulent would pin it to that small section instead).
  -->
  <div class="chapter-wrap chapter-wrap-konsulent">
    {#if intimacyService?.cta}
      <StickyCta cta={intimacyService.cta} />
    {/if}

  <section class="chapter chapter-konsulent" data-stage-anchor="chapter-konsulent">
    <div class="chapter-inner reveal">
      <p class="chapter-mark">{chapter2.mark}</p>
      <h2 class="chapter-title">{chapter2.title}</h2>
      <p class="chapter-lede">{chapter2.lede}</p>
    </div>
  </section>

  {#if intimacyService}
    <section class="service service-intimacy" id={intimacyService.slug} data-stage-anchor="service-intimacy">
      <div class="service-head reveal">
        <span class="s-num">{intimacyService.number}</span>
        <span class="s-kicker">{intimacyService.kicker}</span>
      </div>
      <h2 class="service-title reveal">{intimacyService.title}</h2>
      <p class="s-blurb reveal">{intimacyService.blurb}</p>
      <ul class="s-bullets reveal">
        {#each intimacyService.bullets as bullet}
          <li>{bullet}</li>
        {/each}
      </ul>
      <!-- The pull-quote LIVES here, inline with intimacy coordination -->
      <blockquote class="inline-quote reveal">
        <p>{pillQuote}</p>
      </blockquote>
      <!--
        No inline testimonials here — the `<Testimonials>`
        section at the bottom of the page ("Stemmer") already
        curates voices across services, so repeating the
        intimacy-specific list mid-scroll doubled the content.
      -->

      {#if intimacyService.studios?.length && intimacyService.studiosLabel}
        <div class="studios reveal">
          <p class="studios-lede">{intimacyService.studiosLabel}</p>
          <ul class="studios-list">
            {#each intimacyService.studios as studio}
              <li>
                {#if studio.url}
                  <a href={studio.url} target="_blank" rel="noopener">
                    <img src={studio.logo} alt={studio.name} loading="lazy" />
                  </a>
                {:else}
                  <img src={studio.logo} alt={studio.name} loading="lazy" />
                {/if}
              </li>
            {/each}
          </ul>
        </div>
      {/if}
    </section>
  {/if}

  {#if elderlyService}
    <section class="service service-elderly" id={elderlyService.slug} data-stage-anchor="service-elderly">
      <div class="service-head reveal">
        <span class="s-num">{elderlyService.number}</span>
        <span class="s-kicker">{elderlyService.kicker}</span>
      </div>
      <h2 class="service-title reveal">{elderlyService.title}</h2>
      <p class="s-blurb reveal">{elderlyService.blurb}</p>
      <ul class="s-bullets reveal">
        {#each elderlyService.bullets as bullet}
          <li>{bullet}</li>
        {/each}
      </ul>
    </section>
  {/if}

  {#if teachingService}
    <section class="service service-teaching" id={teachingService.slug} data-stage-anchor="service-teaching">
      <div class="service-head reveal">
        <span class="s-num">{teachingService.number}</span>
        <span class="s-kicker">{teachingService.kicker}</span>
      </div>
      <h2 class="service-title reveal">{teachingService.title}</h2>
      <p class="s-blurb reveal">{teachingService.blurb}</p>
      <ul class="s-bullets reveal">
        {#each teachingService.bullets as bullet}
          <li>{bullet}</li>
        {/each}
      </ul>
    </section>
  {/if}

  <section class="for-work" data-stage-anchor="for-work">
    <p class="section-label reveal">{forWork.label}</p>
    <ul>
      {#each forWork.items as reason, i}
        <li class="reveal" style="--d: {i * 60}ms">
          <span class="fy-num">{String(i + 1).padStart(2, '0')}</span>
          <span>{reason}</span>
        </li>
      {/each}
    </ul>
  </section>

  <section class="bio" data-stage-anchor="bio">
    <p class="section-label reveal">{bio.label}</p>
    <div class="bio-grid">
      <figure class="bio-portrait reveal">
        <img
          src="/img/signe.jpg"
          alt={bio.portraitAlt}
          width="1200"
          height="1400"
          loading="lazy"
          decoding="async"
        />
        <figcaption>
          <span class="bio-name">{nameSection.firstName} {nameSection.lastName}</span>
          <span class="bio-pronouns">{bio.pronouns}</span>
        </figcaption>
      </figure>
      <div class="bio-body">
        {#each bio.body as p, i}
          <p class="reveal" style="--d: {i * 80}ms">{p}</p>
        {/each}
      </div>
    </div>
  </section>

  </div><!-- /.chapter-wrap-konsulent — bio is inside so Kom i kontakt stays pinned through the about-section -->

  {#if home.testimonials && home.testimonials.items.length > 0}
    <!--
      Featured testimonials — curated mix across services, not
      tied to a specific chapter. Sits between the bio and the
      contact block as a closing-act of voices before the final CTA.
    -->
    <section class="home-testimonials" data-stage-anchor="testimonials">
      <Testimonials
        items={home.testimonials.items}
        label={home.testimonials.label}
        prevLabel={locale === 'da' ? 'Forrige udtalelse' : 'Previous testimonial'}
        nextLabel={locale === 'da' ? 'Næste udtalelse' : 'Next testimonial'}
      />
    </section>
  {/if}

  <!--
    The `<ContactSection>` + `<SiteFooter>` that used to close
    the page out are now rendered by `(app)/+layout.svelte`
    (common to every content route).
  -->

<style>
  /*
    Shell styles — `.flod` design tokens + gradient bg, sticky
    header, site footer — all moved to `(app)/+layout.svelte`.
    This page inherits every `--bone`/`--graphite`/`--cta-*`
    custom property from the layout via normal CSS cascade.
    Below are only the homepage's section-specific rules.
  */

  /* ============== HERO ============== */
  .hero {
    position: relative;
    min-height: 100vh;
    max-width: 1320px;
    margin: 0 auto;
    padding: clamp(3rem, 8vw, 6rem) 1.25rem clamp(4rem, 9vw, 6rem);
    display: flex;
    flex-direction: column;
    justify-content: center;
  }
  /* NB: deliberately no position/z-index here — that would create a new
     stacking context and break the `mix-blend-mode: difference` on the
     statement's `.ink` spans. Normal flow stacks above the fixed stage
     canvas (z-index: 0) naturally. */

  .name-card {
    font-family: var(--font-mono);
    font-size: 0.72rem;
    letter-spacing: 0.16em;
    text-transform: uppercase;
    color: var(--graphite);
    margin: 0 0 auto;
    padding-bottom: 4rem;
  }
  .name-card span {
    color: var(--graphite-soft);
  }

  .statement {
    font-family: var(--font-serif);
    font-size: clamp(2.8rem, 11vw, 9rem);
    line-height: 0.94;
    letter-spacing: -0.03em;
    font-weight: 400;
    margin: 0 0 3rem;
    max-width: 18ch;
  }
  /* Plain black — the WebGL canvas behind the text doesn't reliably
     participate in CSS mix-blend-mode compositing, so the "dynamic
     inversion over 3D" effect isn't achievable without moving off WebGL. */
  .statement .ink {
    color: var(--graphite);
  }
  .statement .line {
    display: block;
  }
  .statement em {
    font-style: italic;
    font-weight: 500;
    background: linear-gradient(180deg, transparent 66%, var(--tangerine) 66%);
    padding: 0 0.08em;
  }
  .dot {
    color: oklch(0.82 0.22 115);
    display: inline-block;
    transform: translateY(0.02em);
    font-weight: 600;
  }

  .attribution {
    font-family: var(--font-mono);
    font-size: clamp(0.78rem, 1.2vw, 0.92rem);
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: var(--graphite-soft);
    max-width: 54ch;
    margin: 0 0 4rem;
  }

  .hero-scroll {
    display: inline-flex;
    flex-direction: column;
    align-items: center;
    gap: 0.4rem;
    font-family: var(--font-mono);
    font-size: 0.7rem;
    letter-spacing: 0.2em;
    text-transform: uppercase;
    color: var(--graphite-soft);
    margin-top: auto;
  }
  .arrow {
    font-size: 1rem;
    animation: drip 2.4s ease-in-out infinite;
  }
  @keyframes drip {
    0%, 100% { transform: translateY(0); opacity: 0.6; }
    50% { transform: translateY(6px); opacity: 1; }
  }

  /* ============== NAME SECTION ============== */
  .name-section {
    max-width: 1320px;
    margin: 0 auto;
    padding: clamp(4rem, 10vw, 9rem) 1.25rem;
    border-top: 1px solid var(--rule);
  }
  .name-grid {
    display: grid;
    gap: 2.5rem;
  }
  .eyebrow {
    font-family: var(--font-mono);
    font-size: 0.7rem;
    letter-spacing: 0.2em;
    text-transform: uppercase;
    color: var(--graphite-soft);
    margin: 0 0 1rem;
  }
  .name-section h2 {
    font-family: var(--font-serif);
    font-size: clamp(2.4rem, 6vw, 4.5rem);
    line-height: 0.96;
    font-weight: 400;
    letter-spacing: -0.02em;
    margin: 0 0 1rem;
  }
  .name-section h2 em {
    font-style: italic;
    font-weight: 500;
  }
  .pronouns {
    font-family: var(--font-mono);
    font-size: 0.78rem;
    letter-spacing: 0.1em;
    color: var(--graphite);
    margin: 0;
    padding: 0.4rem 0.7rem;
    border: 1px solid var(--graphite);
    display: inline-block;
  }
  .role-line {
    font-family: var(--font-serif);
    font-size: clamp(1.3rem, 2.6vw, 1.8rem);
    line-height: 1.25;
    font-weight: 400;
    margin: 0 0 1.25rem;
    max-width: 32ch;
  }
  .role-sub {
    font-size: 1rem;
    line-height: 1.65;
    max-width: 48ch;
    color: color-mix(in oklch, var(--graphite) 85%, transparent);
    margin: 0;
  }

  /* ============== MANIFEST ============== */
  .manifest {
    max-width: 1320px;
    margin: 0 auto;
    padding: clamp(4rem, 9vw, 8rem) 1.25rem;
    border-top: 1px solid var(--graphite);
  }
  .section-label {
    font-family: var(--font-mono);
    font-size: 0.7rem;
    letter-spacing: 0.2em;
    text-transform: uppercase;
    color: var(--graphite-soft);
    margin: 0 0 3rem;
  }
  .manifest ul {
    list-style: none;
    padding: 0;
    margin: 0;
    display: grid;
    gap: 0;
  }
  .manifest li {
    display: grid;
    grid-template-columns: auto 1fr;
    gap: 1.5rem;
    padding: 2rem 0;
    border-bottom: 1px solid var(--rule);
  }
  .manifest li:first-child {
    border-top: 1px solid var(--rule);
  }
  .m-num {
    font-family: var(--font-mono);
    font-size: 0.74rem;
    letter-spacing: 0.14em;
    color: var(--violet);
    padding-top: 0.4em;
  }
  .manifest p {
    font-family: var(--font-serif);
    font-size: clamp(1.5rem, 4.5vw, 3rem);
    line-height: 1.15;
    letter-spacing: -0.02em;
    font-weight: 400;
    margin: 0;
    max-width: 26ch;
  }
  .manifest em {
    font-style: italic;
    font-weight: 500;
    background: linear-gradient(180deg, transparent 68%, color-mix(in oklch, var(--tangerine) 55%, transparent) 68%);
    padding: 0 0.04em;
  }

  /* ============== RITUAL ============== */
  .ritual {
    max-width: 1320px;
    margin: 0 auto;
    padding: clamp(3rem, 8vw, 7rem) 1.25rem;
    border-block: 1px solid var(--graphite);
    position: relative;
  }
  /* Ritual's tinted bg sits on a pseudo-element with z-index:-2 so it
     paints BEHIND the fixed 3D canvas (z-index:-1) but still above the
     .flod gradient bg. The canvas thus stays visible across the section. */
  .ritual::before {
    content: '';
    position: absolute;
    inset: 0;
    background: var(--bone-2);
    z-index: -2;
    pointer-events: none;
  }
  .ritual-head {
    max-width: 54ch;
    margin-bottom: 3rem;
  }
  .ritual-head h2 {
    font-family: var(--font-serif);
    font-size: clamp(1.9rem, 5vw, 3.2rem);
    line-height: 1;
    letter-spacing: -0.02em;
    font-weight: 400;
    margin: 0;
  }
  .ritual-list {
    list-style: none;
    padding: 0;
    margin: 0;
    display: grid;
    gap: 0;
  }
  .ritual-list li {
    display: grid;
    grid-template-columns: auto 1fr;
    gap: 2rem;
    padding: 2rem 0;
    border-top: 1px solid var(--rule);
    align-items: baseline;
  }
  .ritual-list li:last-child {
    border-bottom: 1px solid var(--rule);
  }
  .r-n {
    font-family: var(--font-mono);
    font-size: 0.8rem;
    letter-spacing: 0.14em;
    color: var(--violet);
  }
  .ritual h3 {
    font-family: var(--font-serif);
    font-size: clamp(1.4rem, 3vw, 2rem);
    font-weight: 500;
    font-style: italic;
    letter-spacing: -0.01em;
    margin: 0 0 0.6rem;
  }
  .ritual p {
    font-size: 1.02rem;
    line-height: 1.65;
    margin: 0;
    max-width: 60ch;
    color: color-mix(in oklch, var(--graphite) 85%, transparent);
  }

  /* ============== CHAPTER DIVIDERS ============== */
  .chapter {
    max-width: 1320px;
    margin: 0 auto;
    padding: clamp(6rem, 14vw, 11rem) 1.25rem clamp(3rem, 7vw, 5rem);
    border-top: 1px solid var(--graphite);
  }
  .chapter-inner {
    display: grid;
    gap: 1rem;
    max-width: 60ch;
  }
  .chapter-mark {
    font-family: var(--font-serif);
    font-style: italic;
    font-size: clamp(4rem, 12vw, 8rem);
    line-height: 1;
    margin: 0;
    color: var(--violet);
  }
  .chapter-title {
    font-family: var(--font-serif);
    font-weight: 400;
    font-size: clamp(2.4rem, 7vw, 5rem);
    line-height: 1;
    letter-spacing: -0.02em;
    margin: 0 0 1rem;
  }
  .chapter-lede {
    font-family: var(--font-serif);
    font-size: clamp(1.15rem, 2.4vw, 1.4rem);
    line-height: 1.5;
    max-width: 48ch;
    margin: 0;
    color: color-mix(in oklch, var(--graphite) 88%, transparent);
  }

  /* ============== SERVICE SECTIONS ============== */
  .service {
    max-width: 1320px;
    margin: 0 auto;
    padding: clamp(3rem, 7vw, 5.5rem) 1.25rem;
    border-top: 1px solid var(--rule);
  }
  .service-head {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    margin-bottom: 1rem;
    font-family: var(--font-mono);
    font-size: 0.72rem;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    max-width: 70ch;
  }
  .s-num {
    color: var(--violet);
    font-size: 0.92rem;
  }
  .s-kicker {
    color: var(--graphite-soft);
  }
  .service-title {
    font-family: var(--font-serif);
    font-size: clamp(2rem, 5vw, 3.4rem);
    line-height: 1.02;
    letter-spacing: -0.02em;
    font-weight: 400;
    margin: 0 0 1.25rem;
    max-width: 22ch;
  }
  .s-blurb {
    font-family: var(--font-serif);
    font-size: clamp(1.15rem, 2.2vw, 1.4rem);
    line-height: 1.45;
    max-width: 48ch;
    margin: 0 0 1.5rem;
    color: color-mix(in oklch, var(--graphite) 90%, transparent);
  }
  .s-bullets {
    list-style: none;
    padding: 0;
    margin: 0 0 1rem;
    font-size: 1rem;
    line-height: 1.85;
    color: color-mix(in oklch, var(--graphite) 82%, transparent);
    max-width: 60ch;
  }
  .s-bullets li::before {
    content: '— ';
    color: var(--violet);
  }
  .s-supports-block {
    margin-top: 1.25rem;
    padding-top: 1rem;
    border-top: 1px dashed var(--rule);
    max-width: 60ch;
  }
  .s-supports-label {
    font-family: var(--font-mono);
    font-size: 0.72rem;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    margin: 0 0 0.5rem;
    color: var(--graphite-soft);
  }
  .s-supports {
    font-family: var(--font-serif);
    font-style: italic;
    font-size: clamp(1.1rem, 2vw, 1.25rem);
    line-height: 1.5;
    margin: 0;
    color: color-mix(in oklch, var(--graphite) 88%, transparent);
  }

  /* Intimacy coordination — pull-quote + testimonial live inside the section */
  .service-intimacy .inline-quote {
    margin: 2rem 0 0;
    padding: 1.5rem 0 0;
    border-top: 2px solid var(--graphite);
    max-width: 32ch;
  }
  .service-intimacy .inline-quote p {
    font-family: var(--font-serif);
    font-style: italic;
    font-size: clamp(1.35rem, 3vw, 2rem);
    line-height: 1.2;
    letter-spacing: -0.015em;
    font-weight: 400;
    margin: 0;
    color: var(--graphite);
  }
  /* `.s-testimonial` was the inline pullquote under the intimacy
     service card — removed in favour of the bottom `Stemmer`
     section (which uses the <Testimonials> component). CSS
     cleaned up with the markup. */

  /* ============== CHAPTER WRAPPERS ============== */
  /*
    Each chapter wrap bounds a section group. The `<StickyCta>` at the
    top of each wrap uses position: sticky to pin to viewport bottom
    while scrolling through the wrap; when the wrap's bottom edge
    scrolls past the sticky threshold, the CTA exits with the container
    naturally. See StickyCta.svelte for details.
  */
  .chapter-wrap {
    position: relative;
    /*
      Inner padding-bottom equal to the CTA's viewport-bottom gutter.
      Sticky-positioned children are clamped by the containing block's
      content box — so this padding shortens the region in which the
      CTA can stay pinned. Result: when the wrap's bottom approaches
      the chapter divider, the CTA releases with a gap of --cta-v
      between its bottom edge and the divider, matching the gap it
      has to the viewport bottom while pinned.
    */
    padding-bottom: var(--cta-v);
  }
  /*
    chapter-wrap-konsulent has a chapter divider ABOVE it (the chapter-I
    / chapter-II transition). Padding-top: var(--cta-v) pushes the
    Kom i kontakt CTA's natural position down by the same gap the
    Book en tid CTA has to its own bottom divider — so both CTAs have
    symmetric breathing room at their chapter boundaries.
  */
  .chapter-wrap-konsulent {
    padding-top: var(--cta-v);
  }

  /*
    Book en tid initial position + sink-on-scroll.

    At page load we want the button to sit in the hero between the
    lead-in paragraph and the MÆRK ↓ scroll indicator — not yet at
    its eventual bottom-right sticky position. As the user scrolls
    the first ~50vh, the button smoothly descends to its pinned
    sticky target. After that it behaves like a regular sticky-top
    element (pinned until chapter-wrap-therapi's bottom pushes it
    up at the chapter divider).

    Implementation: scroll-driven CSS animation animating the `top`
    value. Sticky re-evaluates on each frame based on the current
    `top`, so the element smoothly glides from 78vh to the sticky
    target as scroll progresses. Modern browsers only — older
    browsers fall back to the static sticky-top value declared on
    the element, so the button just starts at its pinned position.
  */
  @keyframes cta-sink {
    from {
      top: 78vh;
    }
    to {
      top: calc(100dvh - var(--cta-h-box) - var(--cta-v));
    }
  }
  @supports (animation-timeline: scroll()) {
    .chapter-wrap-therapi :global(.sticky-cta) {
      animation: cta-sink linear both;
      animation-timeline: scroll(root);
      animation-range: 0 50vh;
    }
  }
  /*
    The StickyCta is the first child of each wrap and takes up
    --cta-h-box of vertical space in flow. Pull the SECOND child
    (the first real section) up by exactly that amount so the
    visual layout starts at the top of the wrap, unaffected by
    the button's presence. Doing this on the next sibling rather
    than via a negative margin-bottom on the CTA itself preserves
    the CTA's margin-box height, which is what sticky containment
    uses to decide when to release.
  */
  .chapter-wrap > :nth-child(2) {
    margin-top: calc(-1 * var(--cta-h-box));
  }
  /*
    chapter-wrap-konsulent also has padding-top: var(--cta-v) so the
    Kom i kontakt CTA's natural position sits below the divider with
    a gap. That extra top padding would otherwise push the
    chapter-konsulent section (and its black border-top) down by the
    same amount — which visually separates the divider from the bg
    color change. Pull chapter-konsulent up by the extra gap too so
    the divider line lands exactly at the bg transition.
  */
  .chapter-wrap-konsulent > :nth-child(2) {
    margin-top: calc(-1 * (var(--cta-h-box) + var(--cta-v)));
  }

  /* ============== STUDIO CREDITS ============== */
  .studios {
    margin-top: 2.25rem;
    padding-top: 1.5rem;
    border-top: 1px solid var(--rule);
  }
  .studios-lede {
    font-family: var(--font-mono);
    font-size: 0.68rem;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    color: var(--graphite-soft);
    margin: 0 0 1.1rem;
  }
  /* Single row, scrolls sideways when more logos are added. */
  .studios-list {
    list-style: none;
    margin: 0;
    padding: 0 0 0.25rem;
    display: flex;
    gap: 2.25rem;
    flex-wrap: nowrap;
    align-items: center;
    overflow-x: auto;
    overflow-y: hidden;
    scrollbar-width: thin;
    scrollbar-color: color-mix(in oklch, var(--graphite) 25%, transparent) transparent;
  }
  .studios-list::-webkit-scrollbar {
    height: 3px;
  }
  .studios-list::-webkit-scrollbar-thumb {
    background: color-mix(in oklch, var(--graphite) 25%, transparent);
    border-radius: 2px;
  }
  .studios-list li {
    margin: 0;
    flex-shrink: 0;
  }
  .studios-list img {
    display: block;
    /* Explicit height ensures SVGs without intrinsic width/height attrs
       compute a non-zero size (they'd otherwise collapse to 0×0 because
       max-height doesn't establish a concrete dimension for the browser
       to derive aspect-ratio-based width from). */
    height: 40px;
    width: auto;
    color: var(--graphite);
    opacity: 0.65;
    transition: opacity 0.2s ease;
  }
  .studios-list a {
    display: block;
    line-height: 0;
  }
  .studios-list a:hover img {
    opacity: 1;
  }

  /* ============== FOR YOU (shared styles for .for-personal + .for-work) ============== */
  .for-personal,
  .for-work {
    max-width: 1320px;
    margin: 0 auto;
    padding: clamp(4rem, 9vw, 7rem) 1.25rem;
    border-top: 1px solid var(--graphite);
  }
  .for-personal ul,
  .for-work ul {
    list-style: none;
    padding: 0;
    margin: 0;
    display: grid;
    gap: 0;
  }
  .for-personal li,
  .for-work li {
    display: grid;
    grid-template-columns: auto 1fr;
    gap: 1.5rem;
    padding: 1.25rem 0;
    border-top: 1px solid var(--rule);
    font-family: var(--font-serif);
    font-size: clamp(1.15rem, 2.4vw, 1.6rem);
    line-height: 1.3;
    align-items: baseline;
  }
  .for-personal li:last-child,
  .for-work li:last-child {
    border-bottom: 1px solid var(--rule);
  }
  .fy-num {
    font-family: var(--font-mono);
    font-size: 0.74rem;
    letter-spacing: 0.14em;
    color: var(--violet);
  }

  /* ============== BIO ============== */
  .bio {
    max-width: 1320px;
    margin: 0 auto;
    padding: clamp(4rem, 9vw, 7rem) 1.25rem;
  }
  .bio-grid {
    display: grid;
    grid-template-columns: 1fr;
    gap: clamp(2rem, 5vw, 4rem);
    align-items: start;
  }
  .bio-portrait {
    margin: 0;
    position: relative;
    max-width: 420px;
  }
  .bio-portrait img {
    display: block;
    width: 100%;
    height: auto;
    aspect-ratio: 6 / 7;
    object-fit: cover;
    /* Subtle warm tint border echoes the konsulent paper */
    box-shadow:
      0 1px 0 color-mix(in oklch, var(--graphite) 10%, transparent),
      0 24px 48px -24px color-mix(in oklch, var(--graphite) 45%, transparent);
    filter: saturate(0.92) contrast(1.02);
  }
  .bio-portrait figcaption {
    margin-top: 1rem;
    display: flex;
    flex-direction: column;
    gap: 0.2rem;
    font-family: var(--font-sans);
    font-size: 0.78rem;
    letter-spacing: 0.12em;
    text-transform: uppercase;
  }
  .bio-portrait .bio-name {
    color: var(--graphite);
    font-weight: 500;
  }
  .bio-portrait .bio-pronouns {
    color: var(--graphite-soft);
    letter-spacing: 0.08em;
    text-transform: none;
    font-style: italic;
    font-family: var(--font-serif);
    font-size: 0.95rem;
  }
  .bio-body p {
    font-family: var(--font-serif);
    font-size: clamp(1.1rem, 2.3vw, 1.5rem);
    line-height: 1.45;
    margin: 0 0 1.5rem;
    max-width: 42ch;
  }
  .bio-body p:last-child {
    margin-bottom: 0;
  }
  @media (min-width: 860px) {
    .bio-grid {
      grid-template-columns: minmax(0, 0.85fr) minmax(0, 1.15fr);
      gap: clamp(3rem, 6vw, 5rem);
      align-items: start;
    }
    .bio-portrait {
      position: sticky;
      top: 6rem;
      max-width: none;
    }
  }

  /* Contact section + footer strip moved to
     $lib/components/ContactSection.svelte and
     $lib/components/SiteFooter.svelte. */

  /* ============== HOME TESTIMONIALS ============== */
  /* Carries the same horizontal gutter as the other bone-background
     sections (hero, manifest, ritual, etc.) so the testimonial
     cards align with the article column above. The Testimonials
     component handles its own internal scroll bleed on mobile. */
  .home-testimonials {
    max-width: 1320px;
    margin: 0 auto;
    padding: clamp(3rem, 8vw, 6rem) 1.25rem clamp(3rem, 8vw, 6rem);
  }

  /* ============== REVEAL STAGGER ============== */
  .reveal,
  .reveal-soft,
  .reveal-slide {
    animation-delay: var(--d, 0ms) !important;
  }

  /* ============== RESPONSIVE ============== */
  /* `.top`, `.contact`, `.foot p` responsive rules live inside
     their own components now (SiteHeader, ContactSection, SiteFooter) —
     Svelte's scoped CSS means selectors for moved elements don't
     match anything in this file's DOM fragment anyway. */
  @media (min-width: 720px) {
    .hero,
    .name-section,
    .chapter,
    .manifest,
    .ritual,
    .service,
    .for-personal,
    .for-work,
    .bio,
    .home-testimonials {
      padding-left: 2rem;
      padding-right: 2rem;
    }
    .name-grid {
      grid-template-columns: minmax(0, 1.2fr) minmax(0, 1fr);
      gap: 4rem;
    }
    .manifest li,
    .ritual-list li,
    .for-personal li,
    .for-work li {
      grid-template-columns: 4rem minmax(0, 1fr);
      gap: 2.5rem;
    }
  }

  @media (min-width: 1024px) {
    .hero,
    .name-section,
    .chapter,
    .manifest,
    .ritual,
    .service,
    .for-personal,
    .for-work,
    .bio,
    .home-testimonials {
      padding-left: 3rem;
      padding-right: 3rem;
    }
  }
</style>
