<!--
  Danish service detail page. Thin route wrapper — the actual
  layout lives in `<ServicePage>`; this file only handles:

    • resolving the locale content bundle
    • emitting <svelte:head>: title, description, canonical,
      hreflang self + EN peer, OpenGraph + Twitter
    • passing everything down into ServicePage

  The EN mirror under `/en/services/[slug]` is structurally
  identical; any change here should be mirrored there.
-->
<script lang="ts">
  import { contentFor } from '$lib/content';
  import { buildServicePageJsonLd, SITE_URL } from '$lib/seo/structured-data';
  import ServicePage from '$lib/components/ServicePage.svelte';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();

  /*
    Locale-resolved content bundle. The shared `(app)/+layout.svelte`
    also reads `data.locale` via `$page.data` to render the header,
    contact section, and footer — so we don't touch the shell here;
    this wrapper only owns the service-specific <svelte:head> and
    hands body props to <ServicePage>.
  */
  const bundle = $derived(contentFor(data.locale));
  const site = $derived(bundle.site);
  const bio = $derived(bundle.bio);
  const contact = $derived(bundle.contact);
  const home = $derived(bundle.home);
  const service = $derived(data.service);

  const canonicalUrl = $derived(`${SITE_URL}/ydelser/${service.slug}`);
  const alternateEn = $derived(
    data.peer ? `${SITE_URL}/en/services/${data.peer.slug}` : null
  );

  const pageTitle = $derived(`${service.title} · ${site.name}`);
  // Meta description caps near ~160 chars — blurbs are typically
  // already concise. Fall back to the tagline if a service's
  // blurb is ever missing.
  const pageDescription = $derived(service.blurb || site.tagline);

  // Per-service OG image — file generated by `pnpm og` from
  // `/og/{id}` (DA) and `/og/en/{id}` (EN) routes. Uses the
  // stable service `id` (filename) so the URL is the same in
  // both locales even when the service's URL slug differs.
  const ogImageUrl = $derived(`${SITE_URL}/img/og/${service.id}.da.jpg`);

  /*
    Service-page JSON-LD: business + person + THIS service +
    BreadcrumbList (Home → Service). Builder handles locale-
    appropriate URL shapes. The crawled <script> tag is static so
    `$derived` is fine even though the values rarely change after
    mount.
  */
  const jsonLd = $derived(
    JSON.stringify(
      buildServicePageJsonLd({
        locale: 'da',
        site,
        bio,
        contact,
        service,
        pageUrl: canonicalUrl,
        homeLabel: 'Forsiden'
      })
    )
  );
</script>

<svelte:head>
  <title>{pageTitle}</title>
  <meta name="description" content={pageDescription} />

  <!-- Canonical + hreflang -->
  <link rel="canonical" href={canonicalUrl} />
  <link rel="alternate" hreflang="da" href={canonicalUrl} />
  {#if alternateEn}
    <link rel="alternate" hreflang="en" href={alternateEn} />
  {/if}
  <link rel="alternate" hreflang="x-default" href={canonicalUrl} />

  <!-- OpenGraph -->
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content={site.name} />
  <meta property="og:title" content={pageTitle} />
  <meta property="og:description" content={pageDescription} />
  <meta property="og:locale" content="da_DK" />
  {#if alternateEn}
    <meta property="og:locale:alternate" content="en_US" />
  {/if}
  <meta property="og:url" content={canonicalUrl} />
  <meta property="og:image" content={ogImageUrl} />
  <meta property="og:image:alt" content={service.title} />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:type" content="image/jpeg" />

  <!-- Twitter / X -->
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content={pageTitle} />
  <meta name="twitter:description" content={pageDescription} />
  <meta name="twitter:image" content={ogImageUrl} />

  <!--
    Structured data — business + person + this Service +
    BreadcrumbList. Pre-serialised in the script block above so
    the output is a static string by the time the head renders.
    `{@html}` is safe here because `buildServicePageJsonLd` only
    produces JSON and we're the ones constructing the script tag.
  -->
  {@html `<script type="application/ld+json">${jsonLd}</script>`}
</svelte:head>

<ServicePage
  service={data.service}
  {bundle}
  backLabel="Forsiden"
  backHref="/"
  manifest={service.chapter === 'terapi' ? home.manifest : undefined}
  ritual={service.chapter === 'terapi' ? home.ritual : undefined}
  forPersonal={service.chapter === 'terapi' ? home.forPersonal : undefined}
/>
